### ISSUE TITLE
Get rid of Provider/inject in favor of useContext

### ISSUE THREAD

**Issue by zishe** [nareshbhatia/graphql-bookstore#5]
How's about to remove `Provider` in favor of `useConext`?

**Comment by zishe** [comment]
Check out my commit, it works the same. How do you like this style? And it's possible to do the same with styles. I feel this style is shorter and less complex.

**Comment by zishe** [comment]
I checked your new project, so it seems it's still necessary to use Provider.

```ts
                <RootStoreContext.Provider value={rootStore}>
                    <Router />
                </RootStoreContext.Provider>
```

**Comment by nareshbhatia** [comment]
You must be referring to my [manage-my-money](
https://github.com/nareshbhatia/manage-my-money/blob/master/mmm-client/src/App.tsx#L24-L26)
project. Yes, provider is still needed but now its the React context
provider instead of the MobX provider. Also note that I am using
mobx-react@6 for this project.

**Comment by nareshbhatia** [comment]
You must be referring to my [manage-my-money](https://github.com/nareshbhatia/manage-my-money/blob/master/mmm-client/src/App.tsx#L24-L26) project. Yes, provider is still needed but now its the React context provider instead of the MobX provider. Also note that I am using mobx-react@6 for this project.

**Comment by zishe** [comment]
Got it, thanks. That project is awesome!
